# Generated by Django 2.2.6 on 2019-11-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='preset_file',
            field=models.FileField(blank=True, null=True, upload_to='luts/'),
        ),
    ]
