# Generated by Django 2.2.6 on 2019-11-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0002_preset_preset_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preset',
            options={'ordering': ['preset_name']},
        ),
        migrations.AlterModelOptions(
            name='presetpack',
            options={'ordering': ['pack_name']},
        ),
    ]
