# Generated by Django 2.2.6 on 2019-11-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0003_auto_20191112_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='preset_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_pack', to='lg_app.PresetPack'),
        ),
    ]
