# Generated by Django 2.2.6 on 2019-11-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0006_auto_20191114_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
