# Generated by Django 2.2.6 on 2019-11-14 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0007_auto_20191114_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
