# Generated by Django 2.2.6 on 2019-11-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0008_userupload_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset', to='lg_app.Preset')),
                ('user_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_upload', to='lg_app.UserUpload')),
            ],
        ),
    ]
