# Generated by Django 2.2.6 on 2019-11-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0009_presetapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetapplied',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
