# Generated by Django 2.2.6 on 2019-11-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0010_auto_20191114_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='user_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
