# Generated by Django 2.2.6 on 2019-11-15 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lg_app', '0011_auto_20191114_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PresetApplied',
            new_name='ProcessedImage',
        ),
        migrations.RenameModel(
            old_name='UserUpload',
            new_name='UploadedImage',
        ),
    ]
