# Generated by Django 2.2.6 on 2019-11-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0014_auto_20191115_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetpack',
            name='pack_cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
