# Generated by Django 2.2.6 on 2019-11-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0016_uploadedimage_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
