# Generated by Django 2.2.6 on 2019-11-17 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0017_processedimage_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='preset',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_images', to='lg_app.Preset'),
        ),
    ]
