# Generated by Django 2.2.6 on 2019-11-17 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0018_auto_20191116_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='preset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_images', to='lg_app.Preset'),
        ),
    ]
