# Generated by Django 2.2.6 on 2019-11-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0019_auto_20191116_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
