# Generated by Django 2.2.6 on 2019-11-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0020_auto_20191116_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='preset_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/preset_thumbnails'),
        ),
        migrations.AlterField(
            model_name='presetpack',
            name='pack_cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/cover_images'),
        ),
        migrations.AlterField(
            model_name='presetpack',
            name='pack_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/cover_thumbnails'),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='image',
            field=models.ImageField(upload_to='images/after/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='user_img',
            field=models.ImageField(upload_to='images/before/'),
        ),
    ]
