# Generated by Django 2.2.6 on 2019-11-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0021_auto_20191117_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetpack',
            name='pack_fave',
            field=models.BooleanField(default=False),
        ),
    ]
