# Generated by Django 2.2.6 on 2019-11-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0022_presetpack_pack_fave'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetpack',
            name='pack_description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
