# Generated by Django 2.2.6 on 2019-11-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0023_presetpack_pack_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetpack',
            name='pack_description',
            field=models.TextField(max_length=200),
        ),
    ]
