# Generated by Django 2.2.6 on 2019-11-18 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0024_auto_20191117_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='preset_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='lg_app.PresetPack'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
