# Generated by Django 2.2.6 on 2019-11-19 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lg_app', '0025_auto_20191118_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presetpack',
            name='pack_fave',
        ),
        migrations.AddField(
            model_name='presetpack',
            name='pack_fave',
            field=models.ManyToManyField(related_name='favorite_packs', to=settings.AUTH_USER_MODEL),
        ),
    ]
