# Generated by Django 2.2.6 on 2019-11-19 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0026_auto_20191119_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetpack',
            name='pack_fave',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_packs', to=settings.AUTH_USER_MODEL),
        ),
    ]
