# Generated by Django 2.2.6 on 2019-12-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_app', '0028_presetpack_pack_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetpack',
            name='pack_description',
            field=models.TextField(max_length=500),
        ),
    ]
